### ISSUE TITLE
Add !format command

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/hackbot#102]
Add a command summoned by `!format` that displays:

To format code snippets on discord, use triple-backticks and a language name.
For example:
\```dart
void function(type argument) {
  return values;
}
\```
Becomes:
```
void function(type argument) {
  return values;
}
```

**Comment by phelanjo** [comment]
The entire message or just "To format code snippets on discord, use triple-backticks and a language name"?

**Comment by ybakos** [comment]
Whole thing

**Comment by ctsstc** [comment]
Closed by PR #103
