### ISSUE TITLE
Write tests to check all bot commands

### ISSUE THREAD

**Issue by Otis0620** [osu-cascades/hackbot#31]
Find a way to automate how the bots commands are tested. At the moment they are being manually tested, which is slow and error prone.

**Comment by ctsstc** [comment]
While refactoring to a new layout, assuming we go to a command per file, I would like to have a few tests implemented:

1. Check that all commands are valid: They should contain a `description` and `execute` method
  - This should be implemented as a test for all commands not on a per-command basis.
1. Check naming conventions of commands to file name. The class name should match the file name. We will have to determine if we use TitleCase for file names or convert kebab-case to TitleCase.

**Comment by ctsstc** [comment]
This release gets the test coverage up really close, but there still needs some additional work.

https://github.com/osu-cascades/hackbot/releases/tag/v2.1.0

**Comment by ctsstc** [comment]
Closing this now that we use Jest for automated testing.
