### ISSUE TITLE
Configure staging to ignore new member joins

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/hackbot#40]
![screen shot 2017-09-21 at 1 51 29 pm](https://user-images.githubusercontent.com/5502/30718180-fda11572-9ed3-11e7-85f0-4e4bc48eb9f9.png)

**Comment by Otis0620** [comment]
@ybakos ... Is dev branch the code on hackbot-staging and master on hackbot? Or are they both master?

**Comment by Otis0620** [comment]
Fixed in 78bdcc6.
